### ISSUE TITLE
custom_user_profile_fields

### ISSUE THREAD

**Issue by ahruska** [academic-moodle-cooperation/moodle-mod_grouptool#10]
moodle-mod_grouptool custom_user_profile_fields ... es erscheinen in den Teilnehmerlisten NUR bei den Wartelistenteilnehmern die custom user profile fields, nicht bei den Angemeldeten - es gibt eigentlich keinen guten Grund dafür - bitte auch bei Angemeldeten die  custom_user_profile_fields anzeigen!

**Comment by phager-at** [comment]
Entschuldigung für die späte Rückmeldung. Es waren nicht "custom user profile fields" betroffen - die werden hier nämlich nciht angezeigt - sondern die useridentity fields, in den Export Formaten XLSX & ODS (aus Übersichtlichkeits & Layoutgründen wurden diese Felder niemals in TXT und PDF Exporten berücksichtigt).

Wir haben das Problem behoben und die useridentity-Felder sollten ab Version v3.5.1 (veröffentlicht am 05.09.2018) wieder korrekt exportiert werden.
