### ISSUE TITLE
Bug in PDF export of Participants

### ISSUE THREAD

**Issue by SebastianZiegler** [academic-moodle-cooperation/moodle-mod_grouptool#12]
we have a strange behaviour if we export the lists of the participantsas pdf, the 14 th row is empty, so that this participant is missing. The txt export works well.

**Comment by goggo24** [comment]
Could you provide us with some more information: 
Maybe with a screenshot or the pdf without personal data, if possible? 
If the participant isn't anymore in the 14th position, does his/her row still is missing or is it still the 14th row ? If it's related to the participant, does the name of the participant includes any special characters?  Thanks.

**Comment by SebastianZiegler** [comment]
![Bug](https://user-images.githubusercontent.com/2564530/68461310-2dd3b880-020a-11ea-9c6d-186cd270b107.jpeg)
Name is not the problem, if I export another group although the 14th row is empty.

**Comment by goggo24** [comment]
Thanks - we could adjust the error and the fix will be include in v.3.8.0+.

**Comment by goggo24** [comment]
fix included in v.3.8.0 - coming soon!
