### ISSUE TITLE
unenrol from group not possible / delete someone not possible

### ISSUE THREAD

**Issue by SebastianZiegler** [academic-moodle-cooperation/moodle-mod_grouptool#13]
Hello,

we have two problems:

1. if you allow enrolment in multiple groups at once, the attendee hasn't the option to unenrol from group or waiting list

2. we tried to remove someone from a group because he can't do this on his own  (cause of problem 1) but there is no option to do that. So the trainer of the course tried to remove the attendee from the course but then the attendee is still listed in the grouptool

**Comment by goggo24** [comment]
@1: it depends on some settings - most importante setting = allow deregistration has to be yes, than it should be possible to deregister from multiple groups, if you don't get below the minimum group to choose number.
![groups](https://user-images.githubusercontent.com/16721900/74028146-f8c23800-49a9-11ea-862d-6995ca0477f8.png)

@2: In v.3.8.0 (just published) it's possible for teachers to deregsiter students from groups and the grouptool (depending on the sync instance settings)
![deregistration](https://user-images.githubusercontent.com/16721900/74028166-024ba000-49aa-11ea-9405-4723ee8cb285.png) - so this should solve the problem.

**Comment by goggo24** [comment]
If the workflow withl deregistration isn't correct and still doesn't fit, please open a new issue - thanks.
