### ISSUE TITLE
Very slow with many groups

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_grouptool#14]
One of our users created used the grouptool to create 500 groups. Now when a user clicks on the activity it takes so lang that PHP's max execution time (600s for us) is reached and they get a 503 error. I tested it with 50 groups and then the page takes 10 to 15s for the student to load.

So I profiled using xdebug and saw that 6772 SQL queries were being made which took 9214ms in total, so unter 3ms per query. But why are there so many queries?

Just one example of what can be optimized: `get_user_reg_count` and `get_user_queues_count` both call `get_active_groups` without any parameters. Once for each group. In my test that added up to about 7s in total which could be cut in half by reusing the results of `get_active_groups`.

It would be nice if the amount of DB queries in general could be reduced. Over 6000 queries per user clicking on the activity (in a course with 50 groups) is already enormous.

**Edit:** the fact that I had profiling turned on caused PHP to run slower of course (almost by 50%).

**Comment by goggo24** [comment]
We have done some improvements and will check them as part of the overall functionality test for v.3.11 - hopefully this will help and make the situation better.
