### ISSUE TITLE
Support for multilang course names in export filenames

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_grouptool#16]
When your course name uses the multilang format (see https://docs.moodle.org/en/Multi-language_content_filter) and you export participants as a .TXT, .XLSX,. PDF or .ODS file you get something like this as a filename:

```
_span lang=_de_ class=_multilang__gruppenverwaltung test__span__span lang=_en_ class=_multilang__grouptool test__span__50 groups test_User list.ods
```

This can be prevented by calling `format_text` on the course name when building the filename.

**Comment by t-schroeder** [comment]
I fixed this and provided pull requests for the master, 3.8 and 3.7 branches.

**Comment by t-schroeder** [comment]
I started another try at getting this only into the 3.9 branch this time.

**Comment by goggo24** [comment]
Thanks for providing - we will have a look at it.
