### ISSUE TITLE
.TXT and .PDF exports don't respect "showuseridentity" setting

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_grouptool#20]
I've disabled email addresses via the "showuseridentity" setting. But when exporting the participants list as .TXT or .PDF the email address gets exported nonetheless. When exporting as .XLSX or .ODS the setting is respected and no email address gets exported. Is there a reason for that? Otherwise I'd suggest respecting "showuseridentity" for each export format.

**Comment by goggo24** [comment]
Thanks for reporting. You are right - there is a different behaviour between the export formats. We will standardize that.

**Comment by goggo24** [comment]
Fix will be included in v3.11.0 - coming in june
