### ISSUE TITLE
Group creation: Pad created numbers with enough zeros if maximum is 10, 100, 1000

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_grouptool#24]
When creating more than 99 numbered groups (with '#' in the name), all of the numbers that are filled in should get three digits.

Currently, when e.g. creating 100 groups, numbers from 1 to 9 are padded to two digits, but the two-digit numbers don't get a leading zero. This leads group 100 to be alphabetically sorted between group 10 and group 11 in Moodle's own group list.

I see this with Moodle 3.10.6.

**Comment by goggo24** [comment]
Thanks for you feedback. We will add it to our backlog.

**Comment by goggo24** [comment]
As I just saw - it's already implemented. I see the leading zero with v.3.10.0 - can you try it once again?
![image](https://user-images.githubusercontent.com/16721900/138649488-55f01d20-10c3-40a9-9da6-24ecff7aceab.png)

**Comment by jondo** [comment]
Thank you for this feedback! I have now found out that this bug only appears when exactly 10, 100 or 1000 groups are created.

**Comment by goggo24** [comment]
Perfect - thanks for for narrowing down the bug. I will add it in our backlog!

**Comment by goggo24** [comment]
Bug will be fixed in our next version (v.3.11.1) - coming soon.
