### ISSUE TITLE
Hardcoded?

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-mod_grouptool#27]
Thanks for the plugin!
I'm a PT-PT translator.
In Moodle 4.04+(20220915) with last version of the plugin (v4.0.0 - 2022072000) when in english, it shows this (in creation of groups, used sheme name Group # idnumber) :
![imagem](https://user-images.githubusercontent.com/14828021/191025963-118fe75d-2a87-40fb-a99a-62cd2d883311.png)
When you click in "Show group members", it shows:
![imagem](https://user-images.githubusercontent.com/14828021/191028325-4bb260e4-313f-48bf-91c9-591c1d2fc7ac.png)

Changing language to PT (portuguese Portugal)
![imagem](https://user-images.githubusercontent.com/14828021/191028467-523f2795-dcc1-4056-b3d6-e5baf1a8299d.png)
![imagem](https://user-images.githubusercontent.com/14828021/191028695-b1a9b166-035d-4015-b0d6-dcbae76ab7ab.png)

In other places same strings are translated:
![imagem](https://user-images.githubusercontent.com/14828021/191028919-fb9d54ec-3ed5-4a17-953b-cefb2068db17.png)

Any help?
![imagem](https://user-images.githubusercontent.com/14828021/191029923-c84bcf9f-109b-4bea-b968-759962a0a1d5.png)

**Comment by goggo24** [comment]
Thanks for reporting - we will take a look!

**Comment by mkemmerling** [comment]
Fixed with versions 3.11.5 and 4.0.2.
