### ISSUE TITLE
Grading groups returns an error

### ISSUE THREAD

**Issue by LisaE14** [academic-moodle-cooperation/moodle-mod_grouptool#30]
We have a problem to transfer some gradings:

1. There is an assignment and we enter the points in the grader report.
2. Then we want to transfer these points to the other group members via grading in the group tool.
3. The preview works but then we get an error message: Exception - __clone method called on non-object

The error message only appears if we enter the points in the grader report.

Moodle 3.11.11, grouptool v3.11.0 2021051900

**Comment by goggo24** [comment]
Thanks for reporting - we will have a look.

**Comment by goggo24** [comment]
The error occurs only in our 3.11.x version, it's already fixed with from 4.0.x - will you switch to 4.x. soon?

**Comment by LisaE14** [comment]
Thank you for the information. We will switch in August 2023.

**Comment by LisaE14** [comment]
I also get the error with Moodle 4.1.2+ and grouptool 2022072002.

**Comment by LisaE14** [comment]
With moodle 4.1.5 and grouptool 2023062201 we no longer have this problem. Thank you.

**Comment by LisaE14** [comment]
Closing this issue.

**Comment by LisaE14** [comment]
With moodle 4.1.5 and grouptool 2023062201 we no longer have this problem. Thank you.
