### ISSUE TITLE
Highlighting of today on dashboard calendar

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-mod_grouptool#32]
Hi,

why does this plugin add an orange background to the current day in the dashboard calendar block?

![image](https://user-images.githubusercontent.com/24255259/225682885-2b6b502e-8280-4e3c-a707-88515b323db0.png)

Moodle already has an indicator for today.

**Edit:** Sorry, forgot to clarify: This is an issue on Moodle 4. In Moodle 3 there is by default no highlighting for the current day.

**Comment by goggo24** [comment]
Thanks for reporting, we'll have a look.

**Comment by t-schroeder** [comment]
Closing this since it has been fixed with https://github.com/academic-moodle-cooperation/moodle-mod_grouptool/commit/02e9983315c4a3c48dcdf263850c8659de1ce943.
