### ISSUE TITLE
Are groups automatically updated?

### ISSUE THREAD

**Issue by pejhab** [academic-moodle-cooperation/moodle-mod_grouptool#33]
Hello. Are the groups automatically updated when new students enroll in the course?

**Comment by goggo24** [comment]
For every activity you can set the setting "Behaviour on changes in moodle" separately:
![grafik](https://user-images.githubusercontent.com/16721900/235289403-1e81b740-602e-4f71-851e-6ac5150a9eb3.png)

If the student is enrolled automatically (e.g. via registration) in a group and you follow the changes in the grouptool activity, also the infos in grouptool will be updated automatically. Is this, what you have been searching for?
