### ISSUE TITLE
Invalid class names

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-mod_grouptool#4]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions

Classes like `activegroup`, `sortlist` and `sortlist_controller` violate the namespacing rules. Either they must be named with proper frankenstyle prefix, or be namespaced. If you used class autoloading, you would be shielded from this implicitly.

**Comment by mkemmerling** [comment]
Thanks for reporting this, I forwarded the error to our developer.

**Comment by mkemmerling** [comment]
Fxed in version 2015-07-15 (02).
