### ISSUE TITLE
Coding errors might prevent Grouptool English language strings being available for translation in AMOS.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [academic-moodle-cooperation/moodle-mod_grouptool#6]
Hi,
I wanted to translate your Grouptools plugin for Moodle  (which seems to be a very useful addition for my University site)  into Mexican spanish, but there are no English language strings available for translation in AMOS (https://lang.moodle.org/).

Please see the Moodle developer's documentation at  https://docs.moodle.org/dev/Translating_plugins#Plugins_with_coding_errors 

Thanks in advance for your help.

**Comment by mkemmerling** [comment]
Hi German,

the Grouptools is currently in the status 'Incubating' and not yet 'available'. I suppose only available plugins show up in AMOS. The developer is currently working on resolving the remaining issues. Once the plugin available it should show up in AMOS as well.

**Comment by germanvaleroelizondo** [comment]
Hi Markus,

I apologize. I should have checked before :(

All plugins in the 'Other' category are not registered in AMOS as indicated in https://docs.moodle.org/dev/Translating_plugins#Plugins_in_the_Other_category.

I'll be looking forward to translating your plugin once it is moved out of the 'Other' category :)

In the meantime I will translate Moodle documentation at https://docs.moodle.org/28/en/admin/setting/modsettinggrouptool into the Spanish language  at https://docs.moodle.org/all/es/admin/setting/modsettinggrouptool
